import type { ProtectedDomainDetection } from "@/lib/protected-domains/types";
import type {
  ArchitecturalIntakeResult,
  ChangeCategory,
  SuggestedInitiative,
  SuggestedWorkItem,
} from "@/lib/workflow/types";

export function buildArchitecturalBrief(
  result: ArchitecturalIntakeResult,
  rawInput: string,
): string {
  if (result.command === "investment" && result.investment) {
    return buildInvestmentBrief(result, rawInput);
  }

  const lines: string[] = [
    "# Architectural Brief",
    "",
    `> Generated by DevAnvil · Command: \`${result.command}\``,
    "",
    "## Original Input",
    "",
    rawInput,
    "",
    "## Intent",
    "",
    result.intent,
    "",
  ];

  if (result.domains.length > 0) {
    lines.push("## Affected Domains", "");
    for (const d of result.domains) {
      lines.push(
        `### ${d.domain.name}`,
        "",
        `- **Protection Level:** ${d.domain.protectionLevel}`,
        `- **Owner:** ${d.domain.owner}`,
        `- **Risk:** ${d.risk}`,
        "",
      );
      if (d.matchedKeywords.length > 0) {
        lines.push(`**Matched:** ${d.matchedKeywords.join(", ")}`, "");
      }
    }
  } else {
    lines.push("## Affected Domains", "", "_No protected domains detected._", "");
  }

  if (result.protectionSummary.highestLevel) {
    lines.push(
      "## Protection Summary",
      "",
      `- **Highest protection level:** ${result.protectionSummary.highestLevel}`,
    );
    if (result.protectionSummary.requiredContracts.length > 0) {
      lines.push(
        `- **Required contracts:** ${result.protectionSummary.requiredContracts.join(", ")}`,
      );
    }
    if (result.protectionSummary.requiredEvidence.length > 0) {
      lines.push(
        `- **Required evidence:** ${result.protectionSummary.requiredEvidence.join(", ")}`,
      );
    }
    if (result.protectionSummary.requiredTests.length > 0) {
      lines.push(
        `- **Required tests:** ${result.protectionSummary.requiredTests.join(", ")}`,
      );
    }
    lines.push("");
  }

  if (result.changeCategory) {
    lines.push("## Recommended Change Type", "", result.changeCategory, "");
  }

  if (result.memory.length > 0) {
    lines.push("## Architectural Memory", "");
    for (const hit of result.memory.slice(0, 6)) {
      lines.push(`- **${hit.title}** (${hit.source}) — ${hit.snippet}`);
    }
    lines.push("");
  }

  if (result.relatedInitiatives.length > 0) {
    lines.push("## Related Initiatives", "");
    for (const init of result.relatedInitiatives) {
      lines.push(`- ${init.title}${init.isNew ? " _(suggested new)_" : ""}: ${init.rationale}`);
    }
    lines.push("");
  }

  if (result.relatedWorkItems.length > 0) {
    lines.push("## Related Work Items", "");
    for (const item of result.relatedWorkItems.slice(0, 5)) {
      lines.push(
        `- ${item.title} (${Math.round(item.similarityScore * 100)}% match) — ${item.matchReason}`,
      );
    }
    lines.push("");
  }

  if (result.domains.some((d) => d.artifactsToLoad.length > 0)) {
    lines.push("## Architectural Records", "");
    for (const d of result.domains) {
      for (const artifact of d.artifactsToLoad) {
        const path = artifact.path ? ` — \`${artifact.path}\`` : "";
        lines.push(`- [${artifact.kind}] ${artifact.title}${path}`);
      }
    }
    lines.push("");
  }

  if (result.suggestedInitiative) {
    lines.push("## Suggested Initiative", "");
    lines.push(
      `**${result.suggestedInitiative.title}**`,
      result.suggestedInitiative.rationale,
      "",
    );
  }

  if (result.suggestedWorkItems.length > 0) {
    lines.push("## Suggested Work Items", "");
    for (const item of result.suggestedWorkItems) {
      lines.push(
        `### ${item.title}`,
        `- Type: ${item.itemType}`,
        `- ${item.summary}`,
        `- _Rationale:_ ${item.rationale}`,
        "",
      );
    }
  }

  if (result.investigation) {
    lines.push(
      "## Investigation",
      "",
      `**${result.investigation.title}**`,
      "",
      "### Hypotheses",
      ...result.investigation.hypotheses.map((h) => `- ${h}`),
      "",
      "### Suggested Steps",
      ...result.investigation.suggestedSteps.map((s) => `- ${s}`),
      "",
    );
  }

  if (result.shipReport) {
    lines.push("## Ship Report", "");
    if (result.shipReport.blockers.length > 0) {
      lines.push("### Blockers", ...result.shipReport.blockers.map((b) => `- ${b}`), "");
    }
    lines.push(
      `**Ready to ship:** ${result.shipReport.readyToShip ? "Yes" : "No"}`,
      "",
      "### Gates",
      ...result.shipReport.gates.map(
        (g) => `- ${g.passed ? "✓" : "○"} ${g.name}${g.required ? " (required)" : ""}`,
      ),
      "",
    );
  }

  lines.push("## Suggested Next Step", "", result.recommendedNextStep, "");

  lines.push(
    "---",
    "",
    "_This brief is the primary context for Forge and Cursor. Accept to create work items and begin planning._",
  );

  return lines.join("\n");
}

export function buildProtectionSummary(domains: ProtectedDomainDetection[]) {
  const levelOrder = { locked: 4, protected: 3, guarded: 2, advisory: 1 };
  let highestLevel: string | null = null;
  let highestScore = 0;

  const requiredContracts: string[] = [];
  const requiredEvidence: string[] = [];
  const requiredTests: string[] = [];

  for (const d of domains) {
    const score = levelOrder[d.domain.protectionLevel];
    if (score > highestScore) {
      highestScore = score;
      highestLevel = d.domain.protectionLevel;
    }

    for (const artifact of d.artifactsToLoad) {
      if (
        artifact.kind === "runtime_contract" ||
        artifact.kind === "visual_contract"
      ) {
        requiredContracts.push(artifact.title);
      }
      if (artifact.kind === "golden_master") {
        requiredEvidence.push(`Golden master: ${artifact.title}`);
      }
      if (artifact.kind === "test_suite") {
        requiredTests.push(artifact.title);
      }
    }

    for (const gate of d.requiredGates) {
      requiredEvidence.push(gate);
    }
  }

  return {
    highestLevel,
    requiredContracts: [...new Set(requiredContracts)],
    requiredEvidence: [...new Set(requiredEvidence)],
    requiredTests: [...new Set(requiredTests)],
  };
}

export function classifyChange(text: string, hasProtectedDomain: boolean): ChangeCategory {
  const lower = text.toLowerCase();

  if (hasProtectedDomain && /\b(architect|redesign|restructure|new\s+domain)\b/.test(lower)) {
    return "Architectural Change";
  }
  if (/\b(intent|philosophy|mission|non-goal|promise)\b/.test(lower)) {
    return "Intent Evolution";
  }
  if (/\bbug\b|\bbroken\b|\berror\b|\bcrash\b|\bnot\s+working\b/.test(lower)) {
    return "Bug Fix";
  }
  if (/\brefactor\b|\brestructure\b|\bcleanup\b|\brename\b/.test(lower)) {
    return "Refactor";
  }
  if (
    /\bpolish\b|\bfeel\b|\bhover\b|\bscroll\b|\bcramped\b|\bsmoother\b|\btactile\b|\bux\b/.test(
      lower,
    )
  ) {
    return "Polish";
  }
  if (/\bdocument\b|\breadme\b|\bcomment\b/.test(lower)) {
    return "Documentation";
  }
  if (hasProtectedDomain) {
    return "Architectural Change";
  }
  return "Feature";
}

export function suggestWorkItems(
  intent: string,
  title: string,
  summary: string,
  changeCategory: ChangeCategory | null,
): SuggestedWorkItem[] {
  const items: SuggestedWorkItem[] = [];

  if (changeCategory === "Polish" || changeCategory === "Bug Fix") {
    items.push({
      title,
      itemType: changeCategory === "Bug Fix" ? "bug" : "chore",
      summary,
      rationale: `Classified as ${changeCategory}. Scoped change with clear acceptance criteria.`,
    });
    return items;
  }

  items.push({
    title,
    itemType: "feature",
    summary,
    rationale: "Primary work item derived from architectural intake.",
  });

  if (
    intent.toLowerCase().includes("experiment") ||
    intent.toLowerCase().includes("explore")
  ) {
    items.push({
      title: `Research: ${title}`,
      itemType: "opportunity",
      summary: `Explore feasibility and architectural fit for: ${summary}`,
      rationale: "Exploratory work should be separated from implementation.",
    });
  }

  if (changeCategory === "Architectural Change" || changeCategory === "Intent Evolution") {
    items.push({
      title: `ADR: ${title}`,
      itemType: "decision",
      summary: `Document architectural decision for: ${summary}`,
      rationale: "Protected or intent-level changes require explicit decision records.",
    });
  }

  return items;
}

export function suggestInitiative(
  intent: string,
  title: string,
  relatedInitiatives: SuggestedInitiative[],
): SuggestedInitiative | null {
  const existing = relatedInitiatives.find((i) => !i.isNew && i.id);
  if (existing) {
    return {
      id: existing.id,
      title: existing.title,
      rationale: `Aligns with existing initiative "${existing.title}".`,
      isNew: false,
    };
  }

  if (intent.length < 30) return null;

  return {
    title,
    rationale: "New strategic thread detected from intake. Group related work under this initiative.",
    isNew: true,
  };
}

function buildInvestmentBrief(
  result: ArchitecturalIntakeResult,
  rawInput: string,
): string {
  const inv = result.investment!;
  const c = inv.classification;

  const lines: string[] = [
    "# Investment Brief",
    "",
    `> Generated by DevAnvil · Capability-building activity, not implementation work`,
    "",
    "## Original Input",
    "",
    rawInput,
    "",
    "## Investment",
    "",
    `**${c.title}**`,
    "",
    c.summary,
    "",
    "## Capability Target",
    "",
    c.capabilityTarget,
    "",
    "## Category & Leverage",
    "",
    `- **Category:** ${inv.categoryLabel}`,
    `- **Leverage:** ${inv.leverageLabel}`,
    ...(c.estimatedHours ? [`- **Estimated time:** ~${c.estimatedHours} hours`] : []),
    "",
    "## Compounding Value",
    "",
    c.compoundingValue,
    "",
  ];

  if (c.intentConnection) {
    lines.push("## Intent Connection", "", c.intentConnection, "");
  }

  if (c.enablesWork.length > 0) {
    lines.push("## May Enable Future Work", "");
    for (const work of c.enablesWork) {
      lines.push(`- ${work}`);
    }
    lines.push("");
  }

  if (inv.relatedInitiatives.length > 0) {
    lines.push("## Related Initiatives", "");
    for (const init of inv.relatedInitiatives) {
      lines.push(`- ${init.title}: ${init.rationale}`);
    }
    lines.push("");
  }

  if (result.memory.length > 0) {
    lines.push("## Architectural Memory", "");
    for (const hit of result.memory.slice(0, 4)) {
      lines.push(`- **${hit.title}** — ${hit.snippet}`);
    }
    lines.push("");
  }

  lines.push(
    "## Suggested Next Step",
    "",
    result.recommendedNextStep,
    "",
    "---",
    "",
    "_Accept to capture this investment. Complete with a reflection on capability gained — it becomes Architectural Memory._",
  );

  return lines.join("\n");
}
